            <?php

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
            ['page_id' => 1 ,'slug' => 'Switch_Free_and_Direct' ,'eng'=>'Switch Free and Direct to engine Electrable','nl'=>'Schakel vrij en direct naar motor Electrable','fr'=>'Passage libre et direct au moteur électrable'],
            ['page_id' => 1 ,'slug' => 'To_recieve_the' ,'eng'=>'To recieve the prices and discounts as calculated.Please swich via our form before','nl'=>'Om de prijzen en kortingen te ontvangen zoals berekend, neem contact op met ons via',
                             'fr'=>'Pour recevoir les prix et les remises calculés.Veuillez vous inscrire via notre formulaire avant'],
            ['page_id' => 1 ,'slug' => 'First_name' ,'eng'=>'First name','nl'=>'Voornaam','fr'=>'Prénom'],
            ['page_id' => 1 ,'slug' => 'Last_name' ,'eng'=>'Last name','nl'=>'Achternaam','fr'=>'Nom de famille'],
            ['page_id' => 1 ,'slug' => 'Submit' ,'eng'=>'Submit','nl'=>'voorleggen','fr'=>'Soumettre'],
            ['page_id' => 2 ,'slug' => 'Postal_Code' ,'eng'=>'Postal Code','nl'=>'Postcode','fr'=>'code postal'],
            ['page_id' => 2 ,'slug' => 'Family_Size' ,'eng'=>'Family Size','nl'=>'Familie grootte','fr'=>'Taille de la familles'],
            ['page_id' => 2 ,'slug' => 'Electricity' ,'eng'=>'Electricity','nl'=>'Elektriciteit','fr'=>'Électricité'],
            ['page_id' => 2 ,'slug' => 'I_know_my' ,'eng'=>'I know my consumption','nl'=>'Ik ken mijn consumptie','fr'=>'Je connais ma consommation'],
            ['page_id' => 2 ,'slug' => 'Estimate_my' ,'eng'=>'Estimate my consumption','nl'=>'Schat mijn verbruik','fr'=>'Estimer ma consommation'],
            ['page_id' => 2 ,'slug' => 'Meter_Type' ,'eng'=>'Meter Type','nl'=>'Type meter','fr'=>'Type de compteur'],
            ['page_id' => 2 ,'slug' => 'Consumption_Day' ,'eng'=>'Consumption Day','nl'=>'Consumptie dag','fr'=>'Jour de consommation'],
            ['page_id' => 2 ,'slug' => 'Consumption_Night' ,'eng'=>'Consumption Night','nl'=>'Consumptie nacht','fr'=>'Nuit de consommation'],
            ['page_id' => 2 ,'slug' => 'Current_Supplier' ,'eng'=>'Current Supplier','nl'=>'Huidige leverancier','fr'=>'Fournisseur actuel'],
            ['page_id' => 2 ,'slug' => 'Current_Tariff' ,'eng'=>'Current Tariff','nl'=>'Huidig tarief','fr'=>'Tarif actuel'],
            ['page_id' => 2 ,'slug' => 'Contract_Date' ,'eng'=>'Contract Date','nl'=>'Contract datum','fr'=>'Date de contrat'],
            ['page_id' => 2 ,'slug' => 'Gas' ,'eng'=>'Gas','nl'=>'Gas','fr'=>'Gaz'],
            ['page_id' => 2 ,'slug' => 'Consumption' ,'eng'=>'Consumption','nl'=>'Consumptie','fr'=>'Consommation'],
            ['page_id' => 2 ,'slug' => 'Calculate' ,'eng'=>'Calculate','nl'=>'Berekenen','fr'=>'Calculer'],
            ['page_id' => 2 ,'slug' => 'Change_your_data' ,'eng'=>'Change your data','nl'=>'Wijzig uw gegevens','fr'=>'Changer vos données'],
            ['page_id' => 2 ,'slug' => 'Private' ,'eng'=>'Private','nl'=>'Privaat','fr'=>'Privé'],
            ['page_id' => 2 ,'slug' => 'Professional' ,'eng'=>'Professional','nl'=>'professioneel','fr'=>'Professionnel'],
            ['page_id' => 3 ,'slug' => 'Found' ,'eng'=>'Found','nl'=>'gevonden','fr'=>'A trouvé'],
            ['page_id' => 3 ,'slug' => 'Deals' ,'eng'=>'Deals','nl'=>'Aanbiedingen','fr'=>'Offres'],
            ['page_id' => 3 ,'slug' => 'Please_select' ,'eng'=>'Please select a plan for Electricity.','nl'=>'Selecteer een plan voor elektriciteit.','fr'=>"Veuillez sélectionner un plan pour l'électricité."],
            ['page_id' => 3 ,'slug' => 'SORT_BY' ,'eng'=>'SORT BY','nl'=>'SORTEER OP','fr'=>'TRIER PAR'],
            ['page_id' => 3 ,'slug' => 'Compare' ,'eng'=>'Compare','nl'=>'Vergelijken','fr'=>'Comparer'],
            ['page_id' => 3 ,'slug' => 'More_details' ,'eng'=>'More details','nl'=>'Meer details','fr'=>'Plus de détails'],
            ['page_id' => 3 ,'slug' => 'Your_Data' ,'eng'=>'Your Data','nl'=>'Jouw gegevens','fr'=>'Vos données'],
            ['page_id' => 3 ,'slug' => 'Type' ,'eng'=>'Type','nl'=>'Type','fr'=>'Type'],
            ['page_id' => 3 ,'slug' => 'Filter_the_results' ,'eng'=>'Filter the results','nl'=>'Filter de resultaten','fr'=>'Filtrer les résultats'],
            ['page_id' => 3 ,'slug' => 'Display_Results' ,'eng'=>'Display Results','nl'=>'Resultaten weergeven','fr'=>'Afficher les résultats'],
            ['page_id' => 3 ,'slug' => 'Bundle' ,'eng'=>'Bundle','nl'=>'Bundel','fr'=>'Paquet'],
            ['page_id' => 3 ,'slug' => 'separately' ,'eng'=>'separately','nl'=>'afzonderlijk','fr'=>'séparément'],
            ['page_id' => 3 ,'slug' => 'Cost_per' ,'eng'=>'Cost per','nl'=>'Kosten per','fr'=>'Coût par'],
            ['page_id' => 3 ,'slug' => 'Month' ,'eng'=>'Month','nl'=>'Maand','fr'=>'Mois'],
            ['page_id' => 3 ,'slug' => 'Year' ,'eng'=>'Year','nl'=>'Jaar','fr'=>'Année'],
            ['page_id' => 3 ,'slug' => 'Contract_duration' ,'eng'=>'Contract duration','nl'=>'Contractduur','fr'=>'Durée de contrat'],
            ['page_id' => 3 ,'slug' => 'Rate_type' ,'eng'=>'Rate type','nl'=>'Tarieftype','fr'=>'Type de taux'],
            ['page_id' => 3 ,'slug' => 'Discounts' ,'eng'=>'Discounts','nl'=>'Kortingen','fr'=>'Des remises'],
            ['page_id' => 3 ,'slug' => 'Serviced_level' ,'eng'=>'Serviced level limitations','nl'=>'Beperkingen op serviceniveau','fr'=>'Limites de niveau de service'],
            ['page_id' => 3 ,'slug' => 'Green_power' ,'eng'=>'Green power ?','nl'=>'Groene energie ?','fr'=>'Énergie verte ?'],
            ['page_id' => 3 ,'slug' => 'Greenpeace_green' ,'eng'=>'Greenpeace green score','nl'=>'Greenpeace groene score','fr'=>'Greenpeace score vert'],
            ['page_id' => 3 ,'slug' => 'Indefinitely' ,'eng'=>'Indefinitely','nl'=>'Voor onbepaalde tijd','fr'=>'Indéfiniment'],
            ['page_id' => 3 ,'slug' => 'Fixed_price' ,'eng'=>'Fixed price','nl'=>'Vaste prijs','fr'=>'Prix fixe'],
            ['page_id' => 3 ,'slug' => 'Variable_price' ,'eng'=>'Variable price','nl'=>'Variabele prijs','fr'=>'Prix variable'],
            ['page_id' => 3 ,'slug' => 'combinatioin_of_both' ,'eng'=>'combinatioin of both','nl'=>'combinatie van beide','fr'=>'la combinaison des deux'],
            ['page_id' => 3 ,'slug' => 'For_commercial' ,'eng'=>'For commercial','nl'=>'Voor commercieel','fr'=>'Pour commercial'],
            ['page_id' => 3 ,'slug' => 'For_automated_payment' ,'eng'=>'For automated payment','nl'=>'Voor geautomatiseerde betaling','fr'=>'Pour paiement automatisé'],
            ['page_id' => 3 ,'slug' => 'For_digital_invoicing' ,'eng'=>'For digital invoicing','nl'=>'Voor digitale facturering','fr'=>'Pour la facturation numérique'],
            ['page_id' => 3 ,'slug' => 'Automated_payment' ,'eng'=>'Automated payment','nl'=>'Geautomatiseerde betaling','fr'=>'Paiement automatisé'],
            ['page_id' => 3 ,'slug' => 'Digital_invoicing' ,'eng'=>'Digital invoicing','nl'=>'Digitaal factureren','fr'=>'Facturation numérique'],
            ['page_id' => 3 ,'slug' => 'Digital_communication' ,'eng'=>'Digital communication','nl'=>'Digitale communicatie','fr'=>'Communication digitale'],
            ['page_id' => 3 ,'slug' => 'Yes' ,'eng'=>'Yes','nl'=>'Ja','fr'=>'Oui'],
            ['page_id' => 3 ,'slug' => 'Yes_and_Belgian' ,'eng'=>'Yes,and Belgian','nl'=>'Ja en Belgisch','fr'=>'Oui, et belge'],
            ['page_id' => 3 ,'slug' => 'No' ,'eng'=>'No','nl'=>'Nee','fr'=>'Non'],
            ['page_id' => 3 ,'slug' => 'At_least' ,'eng'=>'At least','nl'=>'Tenminste','fr'=>'Au moins'],
            ['page_id' => 3 ,'slug' => 'Email_me' ,'eng'=>'Email me these deals','nl'=>'E-mail mij deze deals','fr'=>'Ecrivez-moi ces offres'],
            ['page_id' => 4 ,'slug' => 'Please_enter' ,'eng'=>'Please enter the e-mail address do you want to send a link to this?','nl'=>'Voer het e-mailadres in. Wilt u hier een link naar sturen?','fr'=>"S'il vous plaît entrer l'adresse e-mail voulez-vous envoyer un lien vers cela?"],
            ['page_id' => 4 ,'slug' => 'Email_Address' ,'eng'=>'Email Address','nl'=>'E-mailadres','fr'=>'Adresse électronique'],
            ['page_id' => 4 ,'slug' => 'I_would_like' ,'eng'=>'I would like to recieve savings tips to save even more on my fixed costs.','nl'=>'Ik ontvang graag besparingen tips om nog meer te besparen op mijn vaste kosten.','fr'=>"Je souhaite recevoir des astuces d'économies pour économiser encore plus sur mes coûts fixes."],
            ['page_id' => 4 ,'slug' => 'Send' ,'eng'=>'Send','nl'=>'Sturen','fr'=>'Envoyer'],
            ['page_id' => 4 ,'slug' => 'We_never_give' ,'eng'=>'We never give your contact details to third party.','nl'=>'Wij geven uw contactgegevens nooit door aan derden.','fr'=>'Nous ne communiquons jamais vos coordonnées à des tiers.'],
            ['page_id' => 5 ,'slug' => 'Back_to_plans' ,'eng'=>'Back to plans','nl'=>'Terug naar plannen','fr'=>'Retour aux plans'],
            ['page_id' => 5 ,'slug' => 'Compare_your' ,'eng'=>'Compare your selection and make choice','nl'=>'Vergelijk uw selectie en maak een keuze','fr'=>'Comparez votre sélection et faites votre choix'],
            ['page_id' => 5 ,'slug' => 'Contract_Details' ,'eng'=>'Contract Details','nl'=>'Contractdetails','fr'=>'Détails du contrat'],
            ['page_id' => 5 ,'slug' => 'Duration' ,'eng'=>'Duration','nl'=>'Looptijd','fr'=>'Durée'],
            ['page_id' => 5 ,'slug' => 'Price_type' ,'eng'=>'Price type','nl'=>'Prijstype','fr'=>'Type de prix'],
            ['page_id' => 5 ,'slug' => 'Source_Power' ,'eng'=>'Source Power','nl'=>'Bron kracht','fr'=>'Puissance de la source'],
            ['page_id' => 5 ,'slug' => 'Who_is_this' ,'eng'=>'Who is this contract for?','nl'=>'Voor wie is dit contract?','fr'=>'Pour qui est ce contrat?'],
            ['page_id' => 5 ,'slug' => 'Particular_Conditions' ,'eng'=>'Particular Conditions','nl'=>'Specifieke omstandigheden','fr'=>'Conditions particulières'],
            ['page_id' => 5 ,'slug' => 'Service_limitations' ,'eng'=>'Service limitations','nl'=>'Service beperkingen','fr'=>'Limites de service'],
            ['page_id' => 5 ,'slug' => 'Documents' ,'eng'=>'Documents','nl'=>'documenten','fr'=>'Les documents'],
            ['page_id' => 5 ,'slug' => 'Product_Description' ,'eng'=>'Product Description','nl'=>'Productomschrijving','fr'=>'Description du produit'],
            ['page_id' => 5 ,'slug' => 'PRICING' ,'eng'=>'PRICING','nl'=>'PRIJZEN','fr'=>'PRIX'],
            ['page_id' => 5 ,'slug' => 'Energy_Cost' ,'eng'=>'Energy Cost','nl'=>'Energiekosten','fr'=>'Coût énergétique'],
            ['page_id' => 5 ,'slug' => 'Fixed_cost' ,'eng'=>'Fixed cost','nl'=>'Vaste kosten','fr'=>'Coûts fixes'],
            ['page_id' => 5 ,'slug' => 'Certificates' ,'eng'=>'Certificates','nl'=>'certificaten','fr'=>'Certificats'],
            ['page_id' => 5 ,'slug' => 'Net_costs' ,'eng'=>'Net costs','nl'=>'Netto kosten','fr'=>'Coûts nets'],
            ['page_id' => 5 ,'slug' => 'Distribution' ,'eng'=>'Distribution','nl'=>'Distributie','fr'=>'Distribution'],
            ['page_id' => 5 ,'slug' => 'Transport' ,'eng'=>'Transport','nl'=>'Vervoer','fr'=>'Transport'],
            ['page_id' => 5 ,'slug' => 'Taxing' ,'eng'=>'Taxing','nl'=>'het belasten','fr'=>'Taxation'],
            ['page_id' => 5 ,'slug' => 'Total' ,'eng'=>'Total','nl'=>'Totaal','fr'=>'Total'],
            ['page_id' => 5 ,'slug' => 'Unit_Prices' ,'eng'=>'Unit Prices','nl'=>'Eenheidsprijzen','fr'=>'Prix unitaires'],
            ['page_id' => 5 ,'slug' => 'These_prices' ,'eng'=>'These prices are only for residential users who sign a new supply contract during MONTH YEAR. Discounts may have a different validity period and specific conditions. All prices include VAT.',
                   'nl'=>'Deze prijzen zijn alleen voor particuliere gebruikers die een nieuw leveringscontract ondertekenen tijdens MAAND JAAR. Kortingen kunnen een andere geldigheidsperiode en specifieke voorwaarden hebben. Alle prijzen zijn inclusief btw.',
                   'fr'=>'Ces prix ne concernent que les utilisateurs résidentiels ayant signé un nouveau contrat de fourniture au cours du MOIS AN. Les remises peuvent avoir une période de validité différente et des conditions spécifiques. Tous les prix incluent la TVA.'],
            
            ['page_id' => 6 ,'slug' => 'Terms_conditions' ,'eng'=>'Terms & conditions','nl'=>'Algemene voorwaarden','fr'=>'Termes et conditions'],
            ['page_id' => 6 ,'slug' => 'Contact' ,'eng'=>'Contact','nl'=>'Contact','fr'=>'Contact'],
            ['page_id' => 6 ,'slug' => 'Frequently_asked' ,'eng'=>'Frequently asked questions','nl'=>'Veel Gestelde Vragen','fr'=>'Questions fréquemment posées'],
            ['page_id' => 6 ,'slug' => 'Powered_by' ,'eng'=>'Powered by','nl'=>'Aangedreven door','fr'=>'Propulsé par'],
            ['page_id' => 6 ,'slug' => 'Copyright' ,'eng'=>'Copyright','nl'=>'auteursrechten','fr'=>"droits d'auteur"],
            
            ];
        DB::table('languages')->delete();
        DB::table('languages')->insert($languages);
    }
}
